### ISSUE TITLE
Choose a name for the distribution of the project

### ISSUE THREAD

**Issue by sapetnioc** [cati-neuroimaging/deidentification#8]
The project will be distributed via `pip` and DockerHub.
Therefore, it must have a globally available name in both environments. This name will also be used as a python module.

**Comment by sapetnioc** [comment]
I propose `cati/deidentification` for Docker and `cati_deidentification` for pip and Python.

**Comment by Hboni** [comment]
I think we need to keep the idea that's for Dicoms in the name.

**Comment by sapetnioc** [comment]
I am not sure. We may extend it to other formats or other modalities in the
future. For instance, removing the file name hidden in `*.nii.gz` files
could be a feature of this tool.

**Comment by sapetnioc** [comment]
Until someone complain and propose something else, the name will be `deidentification` for Pypi and Python module.

**Comment by sapetnioc** [comment]
This issue is closed for now
